[package]
name = "rust-data-structure"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
skiplist = "0.5.1"
rand = "0.8.5"
uuid = {version = "1.3.2", features = ["v6", "v4"]}
